version: "3"

services:
  database-playertype:
    image: postgres:alpine
    restart: always
    expose:
      - 8132
    ports:
      - "8132:5432"
    volumes:
      - playertypedata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=playertype_service
  app-playertype:
    build:
      context: ./../playertype_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: playertype_service
    expose:
      - 8100
      - 8101
    ports:
      - "8100:8100"
      - "8101:8101"
    depends_on:
      - database-playertype
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-playertype:5432/playertype_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-playertype:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "playertype_service",
      "--app-port", "8101",
      "--dapr-http-port", "8100",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../playertype_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-playertype
      - redis
    network_mode: "service:app-playertype"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  playertypedata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true